[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extra_scripts = pre:scripts/inject_version.py
custom_fw_version = 0.1.0
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DASYNC_WEBSERVER_REGEX=1
    -DASYNCWEBSERVER_REGEX=1
lib_deps =
    jgromes/RadioLib@^6.0.0
    ESP32Async/AsyncTCP@^3.4.0
    ESP32Async/ESPAsyncWebServer@^3.7.0
    bblanchon/ArduinoJson@^7.0.0
    h2zero/NimBLE-Arduino@^1.4.3
